# fly.toml app configuration file generated for woom on 2023-10-25T15:11:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "woom"
primary_region = "nrt"

[build]

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
LIVE777_URL = "http://live777.binbat.com:3000"
